#!/usr/bin/python

import matplotlib
matplotlib.use('Qt4Agg')
matplotlib.rcParams['backend.qt4'] = 'PySide'

import sys
from PySide.QtGui import *
from PySide.QtCore import *

from numpy import array
from flare.ui import FlareUi


def main():
    app = QApplication(sys.argv)
    gui = FlareUi()
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()

